# Generated by Django 6.1.1 on 2026-09-24 18:38

import uuid
from decimal import Decimal

import django.db.models.deletion
import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ledger", "0001_initial"),
        ("tenancy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7,
                        editable=False,
                        help_text="Sequential UUIDv7 primary key for high-throughput B-Tree indexing.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Timestamp when record was last updated."
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Legal commercial or individual name.",
                        max_length=255,
                    ),
                ),
                (
                    "contact_type",
                    models.CharField(
                        choices=[
                            ("CUSTOMER", "Customer"),
                            ("SUPPLIER", "Supplier"),
                            ("BOTH", "Customer & Supplier"),
                        ],
                        db_index=True,
                        default="CUSTOMER",
                        help_text="Relationship classification.",
                        max_length=20,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Primary phone number (e.g. +233240000000).",
                        max_length=30,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, help_text="Primary billing email address.", max_length=255
                    ),
                ),
                (
                    "tin",
                    models.CharField(
                        blank=True,
                        help_text="Ghanaian Taxpayer Identification Number (e.g. C0001234567).",
                        max_length=20,
                    ),
                ),
                (
                    "ghana_card_number",
                    models.CharField(
                        blank=True,
                        help_text="Ghana Card National ID PIN (e.g. GHA-123456789-0).",
                        max_length=25,
                    ),
                ),
                (
                    "billing_address",
                    models.TextField(
                        blank=True, help_text="Physical or postal billing address for tax invoices."
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="GHS", help_text="ISO 4217 currency code.", max_length=3
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Soft-activation flag. Inactive contacts cannot accept new invoices.",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Tenant ownership foreign key protected against accidental deletion.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenancy.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact",
                "verbose_name_plural": "Contacts",
                "db_table": "contacts",
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7,
                        editable=False,
                        help_text="Sequential UUIDv7 primary key for high-throughput B-Tree indexing.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Timestamp when record was last updated."
                    ),
                ),
                (
                    "share_token",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unguessable UUIDv4 token for public guest URLs and payment links.",
                        unique=True,
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        db_index=True,
                        help_text="Unique sequence reference or Luhn check number.",
                        max_length=50,
                    ),
                ),
                (
                    "issue_date",
                    models.DateField(db_index=True, help_text="Invoice tax point date."),
                ),
                ("due_date", models.DateField(db_index=True, help_text="Payment due date.")),
                (
                    "subtotal_amount",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        help_text="Net taxable base amount before statutory levies.",
                        max_digits=18,
                    ),
                ),
                (
                    "vat_amount",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        help_text="15.0% Standard VAT under Act 1151.",
                        max_digits=18,
                    ),
                ),
                (
                    "nhil_amount",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        help_text="2.5% National Health Insurance Levy under Act 1151.",
                        max_digits=18,
                    ),
                ),
                (
                    "getfund_amount",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        help_text="2.5% GETFund Levy under Act 1151.",
                        max_digits=18,
                    ),
                ),
                (
                    "covid_levy_amount",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        help_text="Abolished under Act 1151; maintained at 0.0000 for statutory compatibility.",
                        max_digits=18,
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        help_text="Gross total invoice amount payable by customer.",
                        max_digits=18,
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        help_text="Cumulative payments received against this invoice.",
                        max_digits=18,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING_GRA", "Pending GRA Clearance"),
                            ("CLEARED", "Cleared by GRA"),
                            ("PARTIALLY_PAID", "Partially Paid"),
                            ("PAID", "Paid"),
                            ("OVERDUE", "Overdue"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        help_text="Current lifecycle state of the invoice.",
                        max_length=30,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="GHS", help_text="ISO 4217 billing currency.", max_length=3
                    ),
                ),
                (
                    "gra_clearance_code",
                    models.CharField(
                        blank=True,
                        help_text="Cryptographic clearance verification code or SDC ID from GRA.",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "gra_qr_code",
                    models.TextField(
                        blank=True,
                        help_text="Raw or vector SVG payload for official GRA E-VAT QR code.",
                        null=True,
                    ),
                ),
                (
                    "gra_submitted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when invoice was dispatched to GRA clearance service.",
                        null=True,
                    ),
                ),
                (
                    "gra_cleared_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when GRA returned affirmative clearance.",
                        null=True,
                    ),
                ),
                (
                    "pdf_url",
                    models.URLField(
                        blank=True,
                        help_text="Cloudflare R2 pre-signed or public document storage URL.",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(
                        blank=True,
                        help_text="Immutable legal name of customer at invoice issuance.",
                        max_length=255,
                    ),
                ),
                (
                    "customer_tin",
                    models.CharField(
                        blank=True,
                        help_text="Immutable customer TIN at invoice issuance.",
                        max_length=20,
                    ),
                ),
                (
                    "customer_ghana_card",
                    models.CharField(
                        blank=True,
                        help_text="Immutable customer Ghana Card PIN at invoice issuance.",
                        max_length=25,
                    ),
                ),
                (
                    "customer_address",
                    models.TextField(
                        blank=True, help_text="Immutable billing address at invoice issuance."
                    ),
                ),
                (
                    "customer_phone",
                    models.CharField(
                        blank=True,
                        help_text="Immutable customer phone at invoice issuance.",
                        max_length=30,
                    ),
                ),
                (
                    "customer_email",
                    models.CharField(
                        blank=True,
                        help_text="Immutable customer billing email at invoice issuance.",
                        max_length=255,
                    ),
                ),
                (
                    "snapshot_frozen_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the customer legal snapshot was permanently frozen.",
                        null=True,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        help_text="Target customer contact record.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="invoicing.contact",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Tenant ownership foreign key protected against accidental deletion.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenancy.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice",
                "verbose_name_plural": "Invoices",
                "db_table": "invoices",
                "ordering": ["-issue_date", "-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InvoiceLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7,
                        editable=False,
                        help_text="Sequential UUIDv7 primary key for high-throughput B-Tree indexing.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Timestamp when record was last updated."
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Description of goods supplied or service rendered.",
                        max_length=255,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("1.0000"),
                        help_text="Billed quantity or hours.",
                        max_digits=14,
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Price per unit exclusive of statutory levies.",
                        max_digits=18,
                    ),
                ),
                (
                    "line_total",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Total base amount before statutory levies (quantity * unit_price).",
                        max_digits=18,
                    ),
                ),
                (
                    "is_taxable",
                    models.BooleanField(
                        default=True,
                        help_text="Flag indicating whether statutory VAT/NHIL/GETFund apply.",
                    ),
                ),
                (
                    "vat_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.1500"),
                        help_text="Applied VAT rate (15.0% under Act 1151).",
                        max_digits=6,
                    ),
                ),
                (
                    "nhil_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0250"),
                        help_text="Applied NHIL rate (2.5% under Act 1151).",
                        max_digits=6,
                    ),
                ),
                (
                    "getfund_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0250"),
                        help_text="Applied GETFund rate (2.5% under Act 1151).",
                        max_digits=6,
                    ),
                ),
                (
                    "vat_amount",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        help_text="Computed VAT amount for this line.",
                        max_digits=18,
                    ),
                ),
                (
                    "nhil_amount",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        help_text="Computed NHIL amount for this line.",
                        max_digits=18,
                    ),
                ),
                (
                    "getfund_amount",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        help_text="Computed GETFund amount for this line.",
                        max_digits=18,
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Revenue account in general ledger (defaults to 4000 Sales Revenue).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoice_lines",
                        to="ledger.chartofaccounts",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        help_text="Parent invoice header.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="invoicing.invoice",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Tenant ownership foreign key protected against accidental deletion.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenancy.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice Line",
                "verbose_name_plural": "Invoice Lines",
                "db_table": "invoice_lines",
                "ordering": ["created_at"],
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="contact",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="unique_invoicing_contact_tenant_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="contact",
            constraint=models.UniqueConstraint(
                fields=("organization", "name"), name="unique_org_contact_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="unique_invoicing_invoice_tenant_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.UniqueConstraint(
                fields=("organization", "invoice_number"), name="unique_org_invoice_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(("due_date__gte", models.F("issue_date"))),
                name="invoice_check_due_date_after_issue",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(("subtotal_amount__gte", Decimal("0.0000"))),
                name="invoice_check_subtotal_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_amount__gte", Decimal("0.0000"))),
                name="invoice_check_total_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(("paid_amount__gte", Decimal("0.0000"))),
                name="invoice_check_paid_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoiceline",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="unique_invoicing_invoiceline_tenant_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="invoiceline",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", Decimal("0.0000"))),
                name="invoice_line_check_quantity_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoiceline",
            constraint=models.CheckConstraint(
                condition=models.Q(("unit_price__gte", Decimal("0.0000"))),
                name="invoice_line_check_unit_price_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoiceline",
            constraint=models.CheckConstraint(
                condition=models.Q(("line_total__gte", Decimal("0.0000"))),
                name="invoice_line_check_line_total_positive",
            ),
        ),
    ]
