# Generated by Django 6.1.1 on 2026-09-24 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoicing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="payment_reference",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Compact numeric sequence with Luhn check-digit for USSD and MoMo reconciliation.",
                max_length=20,
            ),
        ),
    ]
