# Generated by Django 6.1.1 on 2026-09-22 11:41

import django.core.validators
import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "business_tin",
                    models.CharField(
                        blank=True,
                        help_text="GRA Taxpayer Identification Number (e.g. C0001234567)",
                        max_length=15,
                        null=True,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid GRA Taxpayer Identification Number (e.g., C0001234567).",
                                regex="^[CPGVT]\\d{10}$",
                            )
                        ],
                    ),
                ),
                (
                    "ghana_card_number",
                    models.CharField(
                        blank=True,
                        help_text="Director's Ghana Card PIN (e.g. GHA-123456789-0)",
                        max_length=20,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid Director Ghana Card PIN (e.g., GHA-123456789-0).",
                                regex="^GHA-\\d{9}-\\d$",
                            )
                        ],
                    ),
                ),
                ("address", models.TextField(blank=True)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=255)),
                (
                    "vat_registered",
                    models.BooleanField(
                        default=False,
                        help_text="True if taxable supplies exceed Act 1151 statutory threshold of GHS 750,000",
                    ),
                ),
                (
                    "vat_scheme",
                    models.CharField(
                        choices=[
                            ("STANDARD", "Standard (20.0% Unified Rate)"),
                            ("EXEMPT", "Exempt Supply"),
                            ("ZERO_RATED", "Zero-Rated (Exports)"),
                        ],
                        default="STANDARD",
                        max_length=20,
                    ),
                ),
                (
                    "default_experience_mode",
                    models.CharField(
                        choices=[
                            ("simple", "Simple Mode (Kofi)"),
                            ("full", "Full Accounting Mode (Kwame)"),
                        ],
                        default="simple",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "organizations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrganizationMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("OWNER", "Owner (Principal)"),
                            ("ADMIN", "Admin (General Manager)"),
                            ("ACCOUNTANT", "Accountant (Chartered)"),
                            ("BOOKKEEPER", "Bookkeeper (Data Entry / Cashier)"),
                            ("AUDITOR", "External Auditor (Read-Only Ephemeral)"),
                        ],
                        default="BOOKKEEPER",
                        max_length=30,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "access_expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Configurable expiration timestamp for temporary access (primarily AUDITOR role)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="tenancy.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "organization_memberships",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "user"), name="unique_org_user_membership"
                    )
                ],
            },
        ),
    ]
