# Generated by Django 6.1.1 on 2026-09-23 18:58

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenancy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("1000", "Assets"),
                            ("2000", "Liabilities"),
                            ("3000", "Equity"),
                            ("4000", "Income"),
                            ("5000", "Expenses"),
                        ],
                        help_text="Statutory category prefix code (1000, 2000, 3000, 4000, 5000).",
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Category name (Assets, Liabilities, etc.).", max_length=100
                    ),
                ),
                (
                    "normal_balance",
                    models.CharField(
                        choices=[("DEBIT", "Debit"), ("CREDIT", "Credit")],
                        help_text="Standard normal balance direction for accounts in this category.",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "verbose_name": "Account Category",
                "verbose_name_plural": "Account Categories",
                "db_table": "account_categories",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="ChartOfAccounts",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7,
                        editable=False,
                        help_text="Sequential UUIDv7 primary key for high-throughput B-Tree indexing.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Timestamp when record was last updated."
                    ),
                ),
                (
                    "account_code",
                    models.CharField(
                        help_text="4-digit accounting code (e.g., '1010', '2100', '4000', '5010').",
                        max_length=20,
                    ),
                ),
                (
                    "account_name",
                    models.CharField(
                        help_text="Formal accounting title (e.g., 'Cash on Hand', 'GRA Standard VAT Output').",
                        max_length=150,
                    ),
                ),
                (
                    "simple_label",
                    models.CharField(
                        blank=True,
                        help_text="Simplified human-friendly title for Simple Mode (Kofi).",
                        max_length=150,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="GHS", help_text="Currency ISO code for this account.", max_length=3
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Soft-activation flag. Inactive accounts cannot accept new postings.",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Master category classifying this account.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accounts",
                        to="ledger.accountcategory",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Tenant ownership foreign key protected against accidental deletion.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenancy.organization",
                    ),
                ),
                (
                    "parent_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional parent account for sub-ledger aggregation.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sub_accounts",
                        to="ledger.chartofaccounts",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chart of Accounts",
                "verbose_name_plural": "Charts of Accounts",
                "db_table": "chart_of_accounts",
                "ordering": ["account_code"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FiscalCalendar",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7,
                        editable=False,
                        help_text="Sequential UUIDv7 primary key for high-throughput B-Tree indexing.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Timestamp when record was last updated."
                    ),
                ),
                (
                    "period_length",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("annually", "Annually"),
                        ],
                        default="monthly",
                        help_text="Frequency of financial reporting periods.",
                        max_length=20,
                    ),
                ),
                (
                    "fiscal_year_end_month",
                    models.PositiveSmallIntegerField(
                        default=12,
                        help_text="Month of fiscal year end (1 = January, 12 = December).",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                    ),
                ),
                (
                    "fiscal_year_end_day",
                    models.PositiveSmallIntegerField(
                        default=31,
                        help_text="Day of fiscal year end.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(31),
                        ],
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Tenant ownership foreign key protected against accidental deletion.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenancy.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fiscal Calendar",
                "verbose_name_plural": "Fiscal Calendars",
                "db_table": "fiscal_calendars",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FiscalPeriod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7,
                        editable=False,
                        help_text="Sequential UUIDv7 primary key for high-throughput B-Tree indexing.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Timestamp when record was last updated."
                    ),
                ),
                (
                    "period_name",
                    models.CharField(
                        help_text="Descriptive period label (e.g., 'January 2026', '2026-Q1').",
                        max_length=50,
                    ),
                ),
                ("start_date", models.DateField(help_text="First calendar day of the period.")),
                ("end_date", models.DateField(help_text="Last calendar day of the period.")),
                (
                    "is_closed",
                    models.BooleanField(
                        default=False,
                        help_text="When True, transactions can no longer be posted without signed rectification.",
                    ),
                ),
                (
                    "closed_at",
                    models.DateTimeField(
                        blank=True, help_text="Timestamp when period was locked.", null=True
                    ),
                ),
                (
                    "calendar",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent fiscal calendar defining this period.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="periods",
                        to="ledger.fiscalcalendar",
                    ),
                ),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Authorized user who closed the financial period.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="closed_fiscal_periods",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Tenant ownership foreign key protected against accidental deletion.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenancy.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fiscal Period",
                "verbose_name_plural": "Fiscal Periods",
                "db_table": "fiscal_periods",
                "ordering": ["start_date"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="JournalEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7,
                        editable=False,
                        help_text="Sequential UUIDv7 primary key for high-throughput B-Tree indexing.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Timestamp when record was last updated."
                    ),
                ),
                (
                    "entry_number",
                    models.CharField(
                        help_text="Tenant-scoped unique identifier (e.g. 'JE-2026-00042').",
                        max_length=50,
                    ),
                ),
                (
                    "entry_date",
                    models.DateField(
                        help_text="Formal transaction date for accounting recognition."
                    ),
                ),
                (
                    "narration",
                    models.TextField(
                        help_text="Business description and audit explanation of the transaction."
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("MANUAL", "Manual Journal Entry"),
                            ("INVOICE", "Customer Invoice"),
                            ("BILL", "Vendor Bill"),
                            ("PAYMENT", "Payment Receipt / Disbursement"),
                            ("PAYROLL", "Payroll Run Disbursal"),
                            ("RECTIFICATION", "Prior Period Rectification"),
                        ],
                        default="MANUAL",
                        help_text="Originating operational subsystem.",
                        max_length=50,
                    ),
                ),
                (
                    "source_id",
                    models.UUIDField(
                        blank=True,
                        help_text="Polymorphic UUID reference to originating document (Invoice, Payment, etc.).",
                        null=True,
                    ),
                ),
                (
                    "is_posted",
                    models.BooleanField(
                        default=True,
                        help_text="Immutability lock. Posted entries cannot be updated or deleted via SQL.",
                    ),
                ),
                (
                    "posted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when entry was committed to the general ledger.",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who drafted the entry. Null for automated machine events.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_journal_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Tenant ownership foreign key protected against accidental deletion.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenancy.organization",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        help_text="Fiscal period governing this accounting transaction.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="journal_entries",
                        to="ledger.fiscalperiod",
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who authorized or posted the entry. Null for automated machine events.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posted_journal_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Journal Entry",
                "verbose_name_plural": "Journal Entries",
                "db_table": "journal_entries",
                "ordering": ["-entry_date", "-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="JournalLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7,
                        editable=False,
                        help_text="Sequential UUIDv7 primary key for high-throughput B-Tree indexing.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Timestamp when record was last updated."
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Line-item memo or specific transaction detail.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "debit_amount",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        help_text="Debit value in tenant base currency (GHS).",
                        max_digits=18,
                    ),
                ),
                (
                    "credit_amount",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        help_text="Credit value in tenant base currency (GHS).",
                        max_digits=18,
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        help_text="Target general ledger account.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="journal_lines",
                        to="ledger.chartofaccounts",
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        help_text="Parent journal entry header.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="ledger.journalentry",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Tenant ownership foreign key protected against accidental deletion.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenancy.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Journal Line",
                "verbose_name_plural": "Journal Lines",
                "db_table": "journal_lines",
                "ordering": ["created_at"],
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="chartofaccounts",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="unique_ledger_chartofaccounts_tenant_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="chartofaccounts",
            constraint=models.UniqueConstraint(
                fields=("organization", "account_code"), name="unique_org_account_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="fiscalcalendar",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="unique_ledger_fiscalcalendar_tenant_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="fiscalcalendar",
            constraint=models.UniqueConstraint(
                fields=("organization",), name="unique_org_fiscal_calendar"
            ),
        ),
        migrations.AddConstraint(
            model_name="fiscalperiod",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="unique_ledger_fiscalperiod_tenant_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="fiscalperiod",
            constraint=models.UniqueConstraint(
                fields=("organization", "start_date", "end_date"),
                name="unique_org_fiscal_period_dates",
            ),
        ),
        migrations.AddConstraint(
            model_name="fiscalperiod",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_date__gte", models.F("start_date"))),
                name="fiscal_period_date_range_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="journalentry",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="unique_ledger_journalentry_tenant_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="journalentry",
            constraint=models.UniqueConstraint(
                fields=("organization", "entry_number"), name="unique_org_journal_entry_number"
            ),
        ),
        migrations.AddIndex(
            model_name="journalline",
            index=models.Index(
                fields=["organization", "account", "debit_amount", "credit_amount"],
                name="idx_jl_org_acc_deb_cred",
            ),
        ),
        migrations.AddConstraint(
            model_name="journalline",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="unique_ledger_journalline_tenant_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="journalline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("debit_amount__gte", Decimal("0.0000")),
                    ("credit_amount__gte", Decimal("0.0000")),
                ),
                name="jline_check_positive_values",
            ),
        ),
        migrations.AddConstraint(
            model_name="journalline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("credit_amount", Decimal("0.0000")),
                        ("debit_amount__gt", Decimal("0.0000")),
                    ),
                    models.Q(
                        ("credit_amount__gt", Decimal("0.0000")),
                        ("debit_amount", Decimal("0.0000")),
                    ),
                    _connector="OR",
                ),
                name="jline_check_either_debit_or_credit",
            ),
        ),
    ]
