# Generated by Django 6.1.1 on 2026-09-26 02:00

import django.db.models.deletion
import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenancy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentWebhookLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7,
                        editable=False,
                        help_text="Sequential UUIDv7 primary key.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        db_index=True,
                        help_text="Payment gateway provider (e.g. 'paystack', 'hubtel', 'momo').",
                        max_length=50,
                    ),
                ),
                (
                    "event_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Aggregator event ID (e.g. Paystack event ID or Hubtel client reference).",
                        max_length=255,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        blank=True,
                        help_text="Type of webhook event (e.g. 'charge.success').",
                        max_length=100,
                    ),
                ),
                (
                    "signature_header",
                    models.CharField(
                        blank=True,
                        help_text="Raw cryptographic signature header from the incoming request.",
                        max_length=512,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RECEIVED", "Received"),
                            ("VERIFIED", "Signature Verified"),
                            ("FAILED_SIGNATURE", "Signature Verification Failed"),
                            ("PROCESSED", "Processed"),
                            ("IGNORED", "Ignored"),
                        ],
                        db_index=True,
                        default="RECEIVED",
                        help_text="Current processing and verification status.",
                        max_length=50,
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        default=dict, help_text="Parsed JSON body of the webhook callback."
                    ),
                ),
                (
                    "headers",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Relevant HTTP request headers for security forensics.",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Failure reason or security mismatch description if verification fails.",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the webhook was received.",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated tenant organization once resolved from invoice reference.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_webhook_logs",
                        to="tenancy.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Webhook Log",
                "verbose_name_plural": "Payment Webhook Logs",
                "db_table": "payment_webhook_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["provider", "event_id"], name="payment_web_provide_f12e9a_idx"
                    ),
                    models.Index(
                        fields=["status", "created_at"], name="payment_web_status_cd1680_idx"
                    ),
                ],
            },
        ),
    ]
